name: Matrix
on:
  push:
    branches: main
jobs:
  build:
    strategy:
      matrix:
        versions: [14, 15, 16]
        os: [ubuntu-latest, window-latest]
        include:
          - versions: 18
            os: ubuntu-latest
        exclude:
          - versions: 14
            os: window-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.versions }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Projects
        run: npm run build
