name: Matrix
on: push
jobs:
  build:
    strategy:
      matrix:
        versions: [14, 15, 16]
        os: [ubuntu-latest, window-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.versions }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Projects
        run: npm run build
