name: Reusable workflow
on:
  workflow_call: # para decirle que va hacer llamado desde otro workflow
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        type: string
        default: dist
    secrets:
      some-secret:
        required: true
    outputs:
      resulst:
        description: The resulst of the deploy operation
        value: ${{ jobs.reusabe.outputs.outcome }}
jobs:
  reusabe:
    outputs:
      outcome: ${{ steps.step-resulst.outputs.steps-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List my files
        run: ls -l
      - name: output information
        run: echo "Deploying & uploading ..."
      - name: Get value of secret
        run: echo ${{ secrets.some-secret }}
      - name: Set result output
        id: step-resulst
        run: echo "steps-result=success" >> $GITHUB_OUTPUT
